server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    restart:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dodam?serverTimezone=Asia/Seoul
    username: root
    password: 1234


#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#      #       physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#      use-new-id-generator-mappings: true
#    show-sql: true
#
#    properties:
#      hibernate:
#        format_sql: true
#
#    database: mysql

  jackson:
    serialization:
      fail-on-empty-beans: false

mybatis:
  mapper-locations:        
  - classpath:mapper/**.xml 
  configuration:
    map-underscore-to-camel-case: true # DB의 underscore(snake case) 방식을 Java의 camel case 방식과 매핑